### PR TITLE
Add https:// prefix to description so is clickie

### PR DESCRIPTION
**Pull request by jkoelker**

### CODE REVIEW

**Comment by tr3buchet** [comment]
overridden by another commit making description configurable

**Comment by tr3buchet** [comment]
actually, did you do that on your end and did it make it clicky? cause i did it before and it wasn't clicky then like urls in the description weren't links

**Comment by jkoelker** [comment]
I did, and it does.

**Comment by tr3buchet** [comment]
oh nice, ok they updated then :) totes!

**Pull request closed without merging**
